const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const video=(top,duration=60)=>({isConnected:true,duration,currentTime:10,seekable:{length:0},getClientRects:()=>[1],getBoundingClientRect:()=>({top,bottom:top+640,left:0,right:360})});
let videos=[video(0),video(640)],dialog=false,states=[];
const ctx={location:{protocol:'https:',hostname:'www.instagram.com',pathname:'/reels/'},window:{webkit:{messageHandlers:{reelPaging:{postMessage:s=>states.push(s)}}}},innerHeight:640,innerWidth:360,setInterval:()=>{},document:{querySelectorAll:()=>videos,querySelector:()=>dialog?{}:null}};
vm.runInNewContext(fs.readFileSync(__dirname+'/../Resources/seek.js','utf8'),ctx);
let n=0;const check=fn=>{fn();n++;},update=()=>ctx.window.__rwgSeekUpdate(),seek=(token,t)=>ctx.window.__rwgSeekTo(token,t);
const token=states.at(-1).token;
check(()=>assert.equal(states.at(-1).ready,true));
check(()=>assert.equal(states.at(-1).duration,60));
check(()=>{assert.ok(seek(token,25));assert.equal(videos[0].currentTime,25);assert.equal(videos[1].currentTime,10);});
check(()=>{seek(token,99);assert.equal(videos[0].currentTime,59.99);});
check(()=>{videos[0].seekable={length:1,start:()=>5,end:()=>20};seek(token,35);assert.equal(videos[0].currentTime,20);});
check(()=>assert.equal(seek(token,NaN),false));
check(()=>{videos.reverse();videos[0].getBoundingClientRect=()=>({top:0,bottom:640,left:0,right:360});videos[1].getBoundingClientRect=()=>({top:640,bottom:1280,left:0,right:360});assert.equal(seek(token,40),false);assert.equal(videos[0].currentTime,10);update();assert.notEqual(states.at(-1).token,token);});
check(()=>{videos[0].duration=Infinity;update();assert.equal(states.at(-1).ready,false);});
check(()=>{videos[0].duration=60;ctx.window.__rwgSuspended=true;update();assert.equal(states.at(-1).ready,false);});
check(()=>{ctx.window.__rwgSuspended=false;dialog=true;update();assert.equal(states.at(-1).ready,false);});
check(()=>{dialog=false;ctx.location.pathname='/accounts/login/';update();assert.equal(states.at(-1).ready,false);});
check(()=>{ctx.location.pathname='/reels/';update();assert.equal(states.at(-1).kind,'seek');});
console.log(`${n} native seeking bridge checks passed`);
